collections:
  - name: git+https://github.com/vmware/ansible-for-nsxt
    type: git
  - name: freeipa.ansible_freeipa
  - name: checkmk.general
  - name: chaeynz.namecheap
  - name: community.crypto
  - name: community.dns
