---
- name: Something
  hosts: localhost
  tasks:
    - name: Get a list of all the datacenters
      register: existing_datacenters
      vmware.vmware_rest.vcenter_datacenter_info:

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ existing_datacenters }}"
