---
# This playbook expects vm_info as an artifact in an AWX Workflow
- name: Add Virtual Machines to Netbox
  hosts: localhost
  vars:
    vm_info: "{{ vm_info | mandatory }}"
  tasks:
    - name: Create Virtual Machine object
      netbox.netbox.netbox_virtual_machine:
        data:
          name: "{{ item.guest_name | regex_replace('\\..*', '') }}"
          cluster: "{{ item.cluster }}"
          # tenant: "{{ item.tags | selectattr('category_name', 'equalto', 'Tenant') | map(attribute='name') | list }}"
        state: "{{ _state | default('present') }}"
      loop: "{{ vm_info.virtual_machines }}"
