---
- name: Collect hostname, zone, IPv4, and IPv6 information
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get DNS records from Netbox
      vars:
        query: |
          { {
            netbox_dns_record_list(filters: { NOT: { type: "SOA", OR: { type: "NS"} } }) {
              name, value, type,
              zone { name },
            }
          } }

      ansible.builtin.uri:
        url: "{{ lookup('ansible.builtin.env', 'NETBOX_API') }}"
        method: POST
        headers:
          Authorization: "Token {{ lookup('ansible.builtin.env', 'NETBOX_TOKEN') }}"
        body:
          query: "{ query: {{ query | default('') }} }"
        status_code: 200
        body_format: json
      register: response

    - name: Leave artifacts
      ansible.builtin.set_stats:
        data:
          dns_records: "{{ response.data.netbox_dns_record_list }}"
