---
- name: Create dns record
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Ensure dns record is present
      community.general.ipa_dnsrecord:
        validate_certs: false
        state: "{{ _state | default('present') }}"
        zone_name: "{{ item.zone }}"
        record_name: "{{ item.name }}"
        record_type: "{{ item.type }}"
        record_value: "{{ item.value | ansible.utils.ipaddr('address') }}"
      loop: "{{ dns_records }}"
