---
- name: Upgrade packages on hosts
  hosts: "{{ _hosts | mandatory }}"
  strategy: free
  tasks:
    - name: Gather facts subset
      ansible.builtin.setup:
        gather_subset:
          - pkg_mgr

    - name: Upgrade all dnf packages
      become: true
      ansible.builtin.dnf:
        name: "*"
        state: latest # noqa package-latest
      when: ansible_facts['pkg_mgr'] == 'dnf'

    - name: Update all apt packages
      register: v
      become: true
      ansible.builtin.apt:
        name: "*"
        state: latest # noqa package-latest
      when: ansible_facts['pkg_mgr'] == 'apt'

    - debug:
        msg: "{{ v }}"

    - name: Update all pacman packages
      become: true
      community.general.pacman:
        update_cache: true
        upgrade: true
      when: ansible_facts['pkg_mgr'] == 'pacman'
