---
- name: Gather information from vCenter hosts
  hosts: testcluster
  gather_facts: false
  tasks:
    - name: Gather primary IP and VM name
      set_fact:
        vm_info:
          ip: "{{ primary_ipv4 }}"
          name: "{{ virtual_machine['name'] }}"

- name: Create address object on routers
  vars:
    credentials: &credentials
      hostname: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      tls: true
      validate_certs: false
  hosts: router
  gather_facts: false
  tasks:
    - name: Create address list for each vCenter host
      community.routeros.api_modify:
        <<: *credentials
        path: ip firewall address-list
        data:
          - address: "{{ item.ip }}"
            list: "H_{{ item.name }}"
      with_items: "{{ vcenter_vm_info }}"
      vars:
        vcenter_vm_info: "{{ groups['testcluster'] | map('extract', hostvars, 'vm_info') | list }}"
        
