---
- name: Playbook
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather ethernet interface stats
      vars:
        credentials: &credentials
          hostname: "{{ ansible_host }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          tls: true
          validate_certs: false
      register: interfaces
      community.routeros.api_info:
        <<: *credentials
        path: interface ethernet
