---
- name: Get new IP from Netbox
  hosts: localhost
  tasks:
    - name: Get a new available IP
      register: v
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ lookup('ansible.builtin.env', 'NETBOX_API') }}"
        netbox_token: "{{ lookup('ansible.builtin.env', 'NETBOX_TOKEN') }}"
        data:
          prefix: 203.0.113.0/24
        state: new

    - debug: var=v.ip_address
