---
- name: Gather information from vCenter
  hosts: vcenter
  gather_facts: false
  vars:
    credentials: &credentials
      hostname: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"

  tasks:
    - name: Gather all registered virtual machines
      community.vmware.vmware_vm_info:
        <<: *credentials
      delegate_to: localhost
      register: vm_info
