---
- name: Gather information from vCenter
  hosts: localhost
  gather_facts: false
  vars:
    credentials: &credentials
      validate_certs: false

  tasks:
    - name: Gather all registered virtual machines
      community.vmware.vmware_vm_info:
        <<: *credentials
        show_tag: true
        show_attribute: true
      register: vm_info
    - name:
      ansible.builtin.set_stats:
        data:
          vm_info: "{{ vm_info }}"
