---
- name: Gather information from vCenter
  hosts: localhost
  gather_facts: false
  vars:
    credentials: &credentials
      hostname: "{{ lookup('ansible.builtin.env', 'VMWARE_HOST') }}"
      username: "{{ lookup('ansible.builtin.env', 'VMWARE_USER') }}"
      password: "{{ lookup('ansible.builtin.env', 'VMWARE_PASSWORD') }}"
      validate_certs: false

  tasks:
    - name: Gather all registered virtual machines
      community.vmware.vmware_vm_info:
        <<: *credentials
        show_tag: true
      register: vm_info
    - name:
      ansible.builtin.set_stats:
        data:
          vm_info: "{{ vm_info }}"
