---
- name: Gather information from vCenter
  hosts: localhost
  gather_facts: false
  vars:
    credentials: &credentials
      hostname: "{{ VMWARE_HOST }}"
      username: "{{ VMWARE_USER }}"
      password: "{{ VMWARE_PASSWORD }}"
      validate_certs: false

  tasks:
    - name: Gather all registered virtual machines
      community.vmware.vmware_vm_info:
        <<: *credentials
      register: vm_info
