- name: Reload bird
  become: true
  ansible.builtin.systemd:
    name: bird
    enabled: true
    state: reloaded

- name: Restart birdnotify.service
  become: true
  ansible.builtin.systemd:
    name: birdnotify.service
    state: restarted
    enabled: true
    daemon_reload: true
