---
- name: Listen for all events on a webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        port: "{{ webhook_port | default(5000) }}"
  rules:
    - name: Netbox | Create A and AAAA record
      condition: |
        event.payload.username != "ansible"
      action:
        run_workflow_template:
          name: "Netbox|DNS record"
          organization: Default
          job_args:
            extra_vars:
              dns_records:
                - dns_name: event.payload.data.name
                  dns_zone: event.payload.data.zone.name
                  dns_value: event.payload.data.value
                  dns_type: event.payload.data.type

    - name: Debug
      condition: event.payload is defined
      action:
        debug:
