---
- name: Listen for all events on a webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        port: "{{ webhook_port | default(5000) }}"
  rules:
    - name: Netbox | Create VM
      condition: |
        event.payload.username != "ansible" and
        false
      action:
        run_workflow_template:
          name: "Netbox|Create Virtual Machine"
          organization: Default
          job_args:
            extra_vars:
              virtual_machines:
                - vm_name: event.payload.data.name
                  # datastore:
                  # datacenter: event.payload.cluster.custom_fields.datacenter
                  resource_pool: event.payload.data.custom_fields.resource_pool
                  cluster: event.payload.data.cluster.name

    - name: Debug
      condition: event.payload is defined
      action:
        debug:
