---
- name: Listen for all events on a webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        port: "{{ webhook_port | default(5000) }}"
  rules:
    - name: Netbox | Create A record
      condition:
        all:
          - event.payload.username != "ansible"
          - event.payload.data.tenant != null
          - event.payload.data.primary_ip4 != null
      action:
        run_workflow_template:
          name: "Find tenant DNS zone and create record in zone"
          organization: Default
          job_args:
            extra_vars:
              tenant: "{{ event.payload.data.tenant.name }}"
              name: "{{ event.payload.data.name }}"
              type: A
              value: "{{ event.payload.data.primary_ip4.address }}"

    - name: Netbox | Create AAAA record
      condition:
        all:
          - event.payload.username != "ansible"
          - event.payload.data.tenant != null
          - event.payload.data.primary_ip6 != null
      action:
        run_workflow_template:
          name: "Find tenant DNS zone and create record in zone"
          organization: Default
          job_args:
            extra_vars:
              tenant: "{{ event.payload.data.tenant.name }}"
              name: "{{ event.payload.data.name }}"
              type: AAAA
              value: "{{ event.payload.data.primary_ip6.address }}"

        # TODO: if event.payload.snapshots.prechange.name is defined and != event.payload.snapshots.postchange.name ; do delete_old_dns_name-playbook

    - name: Netbox
      condition: event.payload is defined
      action:
        debug:
