---
- name: Listen for netbox events on a webhook
  hosts: all
  execution_strategy: parallel
  sources:
    - ansible.eda.webhook:
        port: "{{ webhook_port | default(5000) }}"

  rules:

  ## DNS Record
    - name: E/netbox/dnsrecord
      condition: |
        event.payload.model == "record"
      action:
        run_workflow_template:
          name: "E/netbox/dnsrecord"
          organization: Default
          job_args:
            extra_vars:
              dns_records:
                - name: "{{ event.payload.data.name }}"
                  zone: "{{ event.payload.data.zone.name }}"
                  value: "{{ event.payload.data.value }}"
                  type: "{{ event.payload.data.type }}"
              _state: "{{ 'present' if event.payload.event == 'created' or event.payload.event == 'updated' else 'absent' }}"

  ## Virtual Machine created
    - name: E/netbox/virtualmachine
      condition: |
        (
        event.payload.username != "ansible" and
        event.payload.model == "virtualmachine"
        ) and (
        event.payload.data.status.value == "planned" or
        event.payload.data.status.value == "active"
        )
      action:
        run_workflow_template:
          name: E/netbox/virtualmachine
          organization: Default
          job_args:
            extra_vars:
              vm_name: "{{ event.payload.data.name }}"
              platform: "{{ event.payload.data.platform.name }}"
              cluster: "{{ event.payload.data.cluster.name }}"
              tenant: "{{ event.payload.data.tenant.name }}"
              subfolder: "{{ event.payload.data.custom_fields.machine_service_category }}"
              prefix: "{{ event.payload.data.custom_fields.vm_prefix.prefix }}"
              vcpus: "{{ event.payload.data.vcpus }}"
              memory: "{{ event.payload.data.memory }}"

  ## Prefix
    - name: E/netbox/prefix
      condition: |
        (
        event.payload.username != "ansible" and
        event.payload.model == "prefix" and
        event.payload.event == "created"
        ) and (
        event.payload.data.status.value == "planned" or
        event.payload.data.status.value == "active"
        )
      action:
        run_workflow_template:
          name: E/netbox/virtualmachine

  ## Catch all other events and log them
    - name: Debug
      condition: event.payload is defined
      action:
        debug:
