- name: Check if EPEL repo is already configured.
  tags: package
  ansible.builtin.stat:
    path: "{{ epel_repofile_path }}"
  register: epel_repofile_result

- name: Import EPEL GPG key.
  tags: package
  become: true
  ansible.builtin.rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  register: result
  until: result is succeeded
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install EPEL repo.
  tags: package
  become: true
  ansible.builtin.yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: result is succeeded
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists

- name: Ensure bird package is present
  tags: package
  become: true
  ansible.builtin.package:
    name: bird

- name: Permit bgp traffic
  tags: firewall
  become: true
  ansible.posix.firewalld:
    port: 179/tcp
    permanent: true
    immediate: true
    state: enabled

- name: Permit bfd traffic
  tags: firewall
  become: true
  ansible.posix.firewalld:
    port: 3784/udp
    permanent: true
    immediate: true
    state: enabled
