---
- name: Register all hosts to RedHat insights
  hosts: "{{ _hosts | mandatory }}"
  tasks:
    - name: Register the insights client
      redhatinsights.insights.insights_register:
        state: present
      become: true
