---
- name: Create dns record
  hosts: "{{ IPA_HOST }}"
  vars:
    dns_records: "{{ dns_records | mandatory }}"
  tasks:
    - name: Ensure dns record is present
      community.general.ipa_dnsrecord:
        state: "{{ _state | default('present') }}"
        zone_name: "{{ item.zone.name }}"
        record_name: "{{ item.name }}"
        record_type: "{{ item.type }}"
        record_value: "{{ item.value }}"
      loop: "{{ dns_records }}"
