---
- name: Create dns record
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Ensure dns record is present
      community.general.ipa_dnsrecord:
        validate_certs: false
        state: "{{ _state | default('present') }}"
        zone_name: "{{ item.dns_zone }}"
        record_name: "{{ item.dns_name }}"
        record_type: "{{ item.dns_type }}"
        record_value: "{{ item.dns_value }}"
      loop: "{{ dns_records }}"
